name: wearable_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.12.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.31.11
  provider: ^6.1.2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon-512.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon-512.png"